# Generated by Django 3.1.1 on 2020-09-16 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('middlename', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('brgy', models.CharField(max_length=50)),
                ('prov', models.CharField(max_length=50)),
                ('zp', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('height', models.CharField(max_length=20)),
                ('weigth', models.CharField(max_length=20)),
                ('religion', models.CharField(max_length=20)),
                ('sp_name', models.CharField(max_length=50)),
                ('sp_job', models.CharField(max_length=50)),
                ('children', models.CharField(max_length=50)),
                ('m_name', models.CharField(max_length=50)),
                ('m_job', models.CharField(max_length=50)),
                ('f_name', models.CharField(max_length=50)),
                ('f_job', models.CharField(max_length=50)),
                ('profile_pic', models.ImageField(default='placeholder.png', upload_to='')),
            ],
            options={
                'db_table': 'Person',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='customer.person')),
                ('date_regis', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Customer',
            },
            bases=('customer.person',),
        ),
    ]
