# Generated by Django 3.1.1 on 2020-10-15 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='deleted',
            new_name='isdeleted',
        ),
    ]
