# Generated by Django 3.1.1 on 2020-09-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='productImage',
            field=models.ImageField(upload_to='pic_folder/'),
        ),
    ]
