# Generated by Django 3.1.1 on 2020-09-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200916_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='productImage',
            field=models.ImageField(upload_to=''),
        ),
    ]
